@startuml

!define THEME_BG #292929
!define THEME_PANEL #333333
!define THEME_ACCENT #d37070
!define THEME_TEXT #F2F2F2

skinparam backgroundColor THEME_BG
skinparam defaultFontName Arial
skinparam defaultFontColor THEME_TEXT
skinparam componentBackgroundColor THEME_PANEL
skinparam componentBorderColor THEME_ACCENT
skinparam componentFontColor THEME_TEXT
skinparam packageBackgroundColor THEME_PANEL
skinparam packageBorderColor THEME_ACCENT
skinparam packageFontColor THEME_TEXT
skinparam ArrowColor THEME_ACCENT
skinparam noteBackgroundColor THEME_BG
skinparam noteBorderColor THEME_ACCENT
skinparam noteFontColor THEME_TEXT


    person "Utilisateur" as user
    person "Administrateur" as admin

package "Application" {


    component "Single Monolithic Application" as SingleMonolithicApplication {
    
      note "l'application est une app monolithique en TS, HTML et CSS native" as N1
    }
}

user -[hidden]down-> admin

user -right-> SingleMonolithicApplication : "Accéder à l'application en ligne et hors ligne"
admin -right-> SingleMonolithicApplication : "Accéder à l'application en ligne et hors ligne"


@enduml