@startuml
allow_mixing

!define THEME_BG #292929
!define THEME_PANEL #333333
!define THEME_ACCENT #d37070
!define THEME_TEXT #F2F2F2

skinparam backgroundColor THEME_BG
skinparam defaultFontName Arial
skinparam defaultFontColor THEME_TEXT
skinparam componentBackgroundColor THEME_PANEL
skinparam componentBorderColor THEME_ACCENT
skinparam componentFontColor THEME_TEXT
skinparam packageBackgroundColor THEME_PANEL
skinparam packageBorderColor THEME_ACCENT
skinparam packageFontColor THEME_TEXT
skinparam ArrowColor THEME_ACCENT
skinparam personBackgroundColor THEME_BG
skinparam personBorderColor THEME_ACCENT
skinparam personFontColor THEME_TEXT


package "Context" {

    person "Utilisateur" as user
    person "Administrateur" as admin

    component "             Application                " as Application {
    


    }

    component "OpenStreetMap" as OpenStreetMap {
    }

    component "Youtube API" as YoutubeAPI {
    }

    user -right-> Application
    admin -right-> Application

    user -[hidden]down-> admin

    Application -right-> OpenStreetMap : "Récupération des données de localisation"
    Application -right-> YoutubeAPI : "Récupération et affichage des vidéos de présentation"

    OpenStreetMap -[hidden]down-> YoutubeAPI

}


@enduml