@startuml

struct Heroes
{
    + name : string
    + role : string
    + description : string
    + bio : string
    + presentationLines : string[]
    + portrait : string
    + presentationVideo : string
}

struct NPC
{
    + lattitude : number
    + longitude : number
    + icon : string
    + name : string
    + color : string
    + portrait : string
    + presentationVideo : string
}




@enduml