@startuml

!define THEME_BG #292929
!define THEME_PANEL #333333
!define THEME_ACCENT #d37070
!define THEME_TEXT #F2F2F2

skinparam backgroundColor THEME_BG
skinparam defaultFontName Arial
skinparam defaultFontColor THEME_TEXT
skinparam usecaseBackgroundColor THEME_PANEL
skinparam usecaseBorderColor THEME_ACCENT
skinparam usecaseFontColor THEME_TEXT
skinparam personBackgroundColor THEME_BG
skinparam personBorderColor THEME_ACCENT
skinparam personFontColor THEME_TEXT
skinparam ArrowColor THEME_ACCENT
person "Utilisateur" as user
person "Administrateur" as admin

usecase "Consulter un metier" as UC_ConsulterMetier
usecase "Gagner de l'experience" as UC_Experience
usecase "Collecter des badges" as UC_Badges
usecase "Voir plus de details concernant un metier" as UC_DetailsMetier
usecase "Poser et recevoir des réponse concernant un metier" as UC_QuestionsMetier
usecase "Rajouter de nouveau metiers" as UC_AddMetier
usecase "Rajouter de nouveau badges" as UC_AddBadges
usecase "Acceder a l'application en ligne et hors ligne" as UC_AccesApplication
usecase "Se deplacer sur la carte" as UC_SeDeplacerCarte


user --> UC_ConsulterMetier
UC_ConsulterMetier --> UC_DetailsMetier
UC_ConsulterMetier --> UC_QuestionsMetier
user --> UC_Experience
UC_Experience --> UC_Badges
user --> UC_SeDeplacerCarte

user --> UC_AccesApplication
admin --> UC_AccesApplication
admin --> UC_AddMetier
admin --> UC_AddBadges

@enduml